---

- name: Provision possum machine
  hosts: possum.home
  become: true

  roles:
    - role: storage.os
    - role: geerlingguy.pip
    - role: xanmanning.k3s
    - role: local-cert-manager
    - role: storage.apps
